services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - uploads_data:/app/uploads

    env_file:
      - .env

    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}

volumes:
  uploads_data:
